# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ganagroapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='product',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='product',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='client',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='client',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='ganagroapp.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ganagroapp.SubCategory'),
        ),
    ]
