# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ganagroapp', '0005_auto_20170615_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='ganagroapp/img/products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganagroapp.Product')),
            ],
        ),
    ]
