# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ganagroapp', '0006_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
    ]
