# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganagroapp', '0008_auto_20170618_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='products'),
        ),
    ]
