# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganagroapp', '0011_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field=240, upload_to='products', width_field=180),
        ),
    ]
