# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ganagroapp', '0013_auto_20170623_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_width',
        ),
    ]
